spring:
  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://hadoop104:3306/220926?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: "000000"
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath*:/sqls/*Mapper.xml
  configuration:
    mapUnderscoreToCamelCase: true